jobs:
  build:
    name: Build and upload
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Build with Gradle
      run: 'chmod +x gradlew

        ./gradlew build --stacktrace

        '
    - continue-on-error: true
      if: success() || failure()
      name: Publish JUnit report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/build/test-results/test*/TEST-*.xml'
    - continue-on-error: true
      name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@v4
      with:
        name: EssentialsX plugin jars
        path: jars/
name: Build Pull Request
on:
  repository_dispatch:
    types: trigger-ga___build-pr.yml
